set_target/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
end

set_target/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

set_target/app/models/goal.rb
class Goal < ApplicationRecord
  validates :user, :title, presence: true

  belongs_to :user
end

set_target/app/models/user.rb
class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  attr_reader :password


  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return user if user && user.is_password?(password)
    nil
  end
end

set_target/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user
  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    @current_user = User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_login
    redirect_to new_session_url
  end
end

set_target/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = ['invalid login credentials']
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

set_target/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new

  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
  def show
    @user = User.find(params[:id])
  end

end

set_target/app/helpers/application_helper.rb
module ApplicationHelper
end

set_target/app/helpers/sessions_helper.rb
module SessionsHelper
end

set_target/app/helpers/users_helper.rb
module UsersHelper
end

set_target/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SetTarget</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= button_to "Log Out", session_url, method: :delete  %>
    <% else %>
      <%= link_to "Log In", new_session_url %>
      <%= link_to "Sign Up", new_user_url %>
    <% end %>
    <%= yield %>
  </body>
</html>

set_target/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form  action="<%=users_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <label>Username
    <input type="text" name="user[username]" value="">
  </label>
  <label>Password
    <input type="password" name="user[password]" value="">
  </label>
  <input type="submit" name="Sign Up" value="Sign Up">
</form>

set_target/app/views/users/show.html.erb
<%= @user.username %>